name: workflow-commands
on: [push]
jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
            - name: Setting an error with Params
              run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: Setting a debug with Params
              run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: Setting an warning with Params
              run: echo "::warning title=Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
            - name: Setting an notice with Params
              run: echo "::notice title=Notice title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"
